workouts/models/workout.py
from ..database.db import db

class Workout(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    sets = db.relationship('Set', backref='workout', lazy=True, cascade="all, delete")

    def __str__(self):
        return f'<Workout "{self.name}">'

class Set(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    weight = db.Column(db.String(80))
    reps = db.Column(db.String(80))
    workout_id = db.Column(db.Integer, db.ForeignKey('workout.id'),
        nullable=False)
    
    def __str__(self):
        return f'<Set "{self.weight}">'
        

workouts/__init__.py
from dotenv import load_dotenv
from os import environ 
from flask import Flask
from flask_cors import CORS

from .database.db import db
from .routes.main import main_routes

load_dotenv()

database_uri = environ.get('DATABASE_URL')
if 'postgres' in database_uri:
    database_uri = database_uri.replace('postgres:', 'postgresql:')

app = Flask(__name__)
app.config.update(
    SQLALCHEMY_DATABASE_URI=database_uri,
    SQLALCHEMY_TRACK_MODIFICATIONS=environ.get('SQL_ALCHEMY_TRACK_MODIFICATIONS')
)

CORS(app)

db.app = app
db.init_app(app)

app.register_blueprint(main_routes)

if __name__ == "__main__":
    app.run(debug=True)

workouts/routes/main.py
from flask import Blueprint, request, render_template
from flask import jsonify, redirect, url_for
from ..database.db import db
from ..models.workout import Workout
from ..models.workout import Set

main_routes = Blueprint("example", __name__)


@main_routes.route("/", methods=["GET", "POST"])
def home():
    if request.method == "GET":
        workouts = Workout.query.all()
        return render_template("index.html", workouts=workouts)
    else:

        name = request.form["name"]
        weight = request.form["weight"]
        reps = request.form["reps"]

        new_workout = Workout(name=name)
        new_set = Set(weight=weight, reps=reps, workout=new_workout)

        db.session.add(new_workout)
        db.session.add(new_set)
        db.session.commit()

        
        workouts = Workout.query.all()
        return redirect(url_for('example.home'))
       # return redirect(url_for("/"))
       # return f"{new_workout['name']} has been created", 201

@main_routes.route('/delete/<int:id>', methods=['POST'])
def delete_workout(id):
    workout_to_delete = Workout.query.get(id)
    db.session.delete(workout_to_delete)
    db.session.commit()

    return redirect(url_for('example.home'))


@main_routes.route('/about')
def about():
    return "About page"
    

workouts/templates/index.html
{% block title %}Workouts{% endblock %}
{% block content %}
    <h1>Workouts</h1>
    <em>Here's a summary of your workouts:</em>
    <hr />
    <ul>
        {% for workout in workouts %}
            <li class="workout">
                <h2>{{ workout.name }}</h3>
                <form action="{{ url_for('example.delete_workout', id=workout.id) }}" method="POST">
                    <input type="submit" value="Delete">
                </form>
            {% for set in workout.sets %}
                    <p> {{set.weight}}</p>
                    <p> {{set.reps}}</p>
            {% endfor %}
            </li>
        {% endfor %}

    </ul>
    <hr />
    <h2>Add new workout</h2>
    <form method="POST">
        <fieldset>
            <label for="name-input">Name of workout: </label>
            <input type="text" id="name-input" name="name" required />
        </fieldset>
        <fieldset>
            <label for="weight-input">Weight: </label>
            <input type="text" id="weight-input" name="weight" required />
        </fieldset>
        <fieldset class="full-width">
            <label for="reps-input">Reps: </label>
            <textarea id="reps-input" name="reps" required></textarea>
            <input type="submit" value="Submit">
        </fieldset>
    </form>
{% endblock %}